# Generated by Django 5.2.9 on 2026-01-18 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autenticacao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'tipo_evento',
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('data_evento', models.DateField(verbose_name='Data do Evento')),
                ('horario_evento', models.TimeField(verbose_name='Horário do Evento')),
                ('responsavel', models.CharField(max_length=255, verbose_name='Palestrante/Responsável')),
                ('local', models.CharField(max_length=255, verbose_name='Local')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cadastrado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autenticacao.usuario', verbose_name='Usuário que Cadastrou')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='eventos.tipoevento', verbose_name='Tipo de Evento')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'db_table': 'evento',
            },
        ),
    ]
